[package]
name = "marketplace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "23.0.2"
interfaces = { path = "../interfaces" }

[dev-dependencies]
soroban-sdk = { version = "23.0.2", features = ["testutils"] }
